"$schema" = "../../schemas/pakk.mod.schema.json"

name = "pkgb"

[[pkg.pre]]

each = "*.templ"
run = ["go", "tool", "templ", "generate", "-f", "{{ .Item }}"]
generates = ["pkgb_templ.go"]

[pkg.provides.import]

path = ["examples", "pkgb"]
